@startuml SSE Flow

autonumber
participant CLIENT
participant SERVER

CLIENT -> SERVER : initiate handshake
SERVER -> CLIENT : sending message A
SERVER -> CLIENT : sending message B
SERVER -> CLIENT : sending message C
...
SERVER --> CLIENT : Ending the Connection

@enduml